import type { PermissionPolicyConfig } from './types.js';

export const builtInPermissionPolicy: PermissionPolicyConfig = {
  enabled: true,
  workspace: {
    allowRead: 'allow',
    allowWrite: 'allow',
    allowCreate: 'allow',
    list: 'allow',
    search: 'allow',
    followSymlinks: 'realpath',
    ask: ['.git/**', 'node_modules/**'],
    deny: [],
  },
  outsideWorkspace: {
    read: 'ask',
    list: 'ask',
    search: 'ask',
    write: 'ask',
    create: 'ask',
    rememberApprovals: 'session',
  },
  secrets: {
    mode: 'deny',
    denyPaths: [
      '.env',
      '.env.*',
      '**/*.{pem,key,p12,pfx}',
      '**/id_rsa',
      '**/id_ed25519',
      '~/.ssh/**',
      '~/.aws/**',
      '~/.gnupg/**',
      '~/.config/*/credentials*',
      '**/*credential*',
    ],
    denyKeyPatterns: ['api[_-]?key', 'token', 'secret', 'password', 'credential'],
    maxPreviewBytesForPrompt: 0,
  },
  tools: {
    read: 'policy',
    write: 'policy',
    edit: 'policy',
    grep: 'policy',
    find: 'policy',
    ls: 'policy',
    bash: 'policy',
  },
  bash: {
    default: 'ask',
    safeCommands: ['git status', 'git diff', 'npm test', 'npm run typecheck'],
    denyCommands: ['sudo *', 'su *', 'chmod 777 *', 'chown *', 'rm -rf /', 'rm -rf ~', 'curl * | sh', 'wget * | sh'],
    askCommands: ['rm *', 'mv *', 'cp *', 'git clean *', 'git reset *', 'npm install *', 'pnpm add *', 'pip install *'],
    network: 'ask',
    outsideWorkspaceFilesystem: 'ask',
    envSecretExposure: 'deny',
    maxCommandPreviewChars: 240,
  },
  nonInteractive: {
    onAsk: 'deny',
    allowSessionApprovals: false,
  },
  approvals: {
    sessionCache: true,
    allowForSession: true,
  },
  audit: {
    enabled: true,
    logAllowed: false,
    logDenied: true,
    logApprovals: true,
    redactPaths: true,
    maxBytes: 5 * 1024 * 1024,
    maxFiles: 5,
  },
};
