import { resolve } from 'node:path';
import { blockMessage, checkScope, resolveScopeForToolCall } from '../core/scope.js';

function collectPathInputs(toolName: string, input: any): string[] {
  if (!input || typeof input !== 'object') return [];
  if (toolName === 'read') return [input.path, input.file_path].filter((value): value is string => typeof value === 'string');
  if (toolName === 'write' || toolName === 'edit') return [input.path, input.file_path].filter((value): value is string => typeof value === 'string');
  return [];
}

function isDerivedWorkflowJson(cwd: string, path: string): boolean {
  const normalized = resolve(cwd, path).replaceAll('\\', '/');
  const root = resolve(cwd).replaceAll('\\', '/');
  return normalized === `${root}/openspec/workflows.json` || /^.+\/openspec\/changes\/[^/]+\/workflow\.json$/.test(normalized);
}

function isSubagentToolCall(event: any, ctx: any): boolean {
  const candidates = [
    event?.agentType,
    event?.agent_type,
    event?.agentRole,
    event?.agent_role,
    event?.agent?.type,
    event?.agent?.role,
    event?.source,
    event?.scope,
    ctx?.agentType,
    ctx?.agent_type,
    ctx?.agentRole,
    ctx?.agent_role,
    ctx?.agent?.type,
    ctx?.agent?.role,
    ctx?.source,
    ctx?.scope,
  ];
  if (event?.isSubagent === true || event?.is_subagent === true || event?.agent?.isSubagent === true || event?.agent?.is_subagent === true) return true;
  if (ctx?.isSubagent === true || ctx?.is_subagent === true || ctx?.agent?.isSubagent === true || ctx?.agent?.is_subagent === true) return true;
  return candidates.some((value) => typeof value === 'string' && /sub[-_ ]?agent/i.test(value));
}

export async function guardToolCall(event: { toolName?: string; input?: any }, ctx: { cwd: string; ui?: { notify?: (message: string, level?: string) => void } }) {
  const toolName = event.toolName;
  if (toolName !== 'read' && toolName !== 'write' && toolName !== 'edit' && toolName !== 'bash') return undefined;
  const command = typeof event.input?.command === 'string' ? event.input.command : undefined;
  const paths = toolName === 'bash' ? [] : collectPathInputs(toolName, event.input);
  if ((toolName === 'write' || toolName === 'edit') && paths.some((path) => isDerivedWorkflowJson(ctx.cwd, path))) {
    const reason = 'workflow-guard blocked this action.\nReason: derived workflow JSON may only be regenerated by workflow-guard, not edited manually.\nEvidence: openspec/workflows.json or openspec/changes/<slug>/workflow.json.\nNext permitted action: use workflow_validate with repairDerivedJson: true.';
    ctx.ui?.notify?.(reason, 'warning');
    return { block: true, reason };
  }
  if (!isSubagentToolCall(event, ctx)) return undefined;
  const scope = await resolveScopeForToolCall(ctx.cwd, paths);
  if (!scope) return undefined;
  const result = checkScope(scope, { action: toolName, paths, command, cwd: ctx.cwd });
  if (result.allowed) return undefined;
  const reason = blockMessage(result);
  ctx.ui?.notify?.(reason, 'warning');
  return { block: true, reason };
}
